apiVersion: v1
kind: Service
metadata:
  name: developeriq-userauth-service
  namespace: developeriq
  labels:
    app: developeriq
spec:
  selector:
    app: developeriq

  ports:
    - port: 8081
      targetPort: 8081

  type: LoadBalancer